### ISSUE TITLE
Provider produced inconsistent final plan 

### ISSUE THREAD

**Issue by Warns** [cloudposse/terraform-aws-security-group#19]
## Describe the Bug
Using this Security Group module to provide SGs for the Elasticsearch module, at the end of the apply process I'm getting this error. 

```css
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for
│ module.vpc.module.security_group.aws_security_group_rule.default["egress--1-0-65535-1c888a621b808e08e46f9e8b7e217885"] to
│ include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for
│ .security_group_id: was cty.StringVal(""), but now cty.StringVal("sg-028df7d4dafcc68df").
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

This error occurs after around 10 minutes of wait time for ES to be created and it does created with an Active status in the end.

## Expected Behavior
ES and SGs should be created with no errors.

## Steps to Reproduce
- Use the necessary modules to deploy an Elasticsearch service with minimal or no customisation (Using modules as is)

## Screenshots
![image](https://user-images.githubusercontent.com/4021052/128195126-4446713b-e5de-4b32-a5ba-c422a1246d9c.png)

**Comment by Warns** [comment]
For anyone getting errors such as the above or "Security group already exists etc" please check the following first

Thanks to @aknysh on slack for pointing out using the `attributes` in contexts in the modules to make it create resources with different naming. Otherwise if same context is used in every module the names generated will all be the same. Going to fix this first.

**Comment by Nuru** [comment]
@Warns Please note the part of the error message that says:
> This is a bug in the provider, which should be reported in the provider's own issue tracker.

So please report the bug [there](https://github.com/hashicorp/terraform-provider-aws).

When reporting a bug, please indicate the version numbers of everything involved. Here that would be at least:
- Terraform
- The AWS Terraform provider
- This module, `terraform-aws-security-group`
- The Elasticsearch module
