### ISSUE TITLE
Some versions of cloudposse/security-group/aws went away.

### ISSUE THREAD

**Issue by jerowe** [cloudposse/terraform-aws-security-group#22]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
Some modules in the eks stack require security-group 0.3.3, which does not exist in the cloudposse/security-group terraform registry.

[EKS Node Groups](https://registry.terraform.io/modules/cloudposse/eks-node-group/aws/0.24.4#module_security_group)
[EKS Worker Groups](https://registry.terraform.io/modules/cloudposse/eks-workers/aws/0.19.5#module_security_group)
[Security Groups](https://registry.terraform.io/modules/cloudposse/security-group/aws/latest)

<img width="1523" alt="Screen Shot 2021-09-05 at 11 26 30 AM" src="https://user-images.githubusercontent.com/5555526/132120548-a8653d7b-8451-44bc-ab1d-5731eb599f64.png">

## Expected Behavior
Versions should exist.

## Steps to Reproduce

```
# main.tf
    module "eks_node_group" {
      source = "cloudposse/eks-node-group/aws"
      # Cloud Posse recommends pinning every module to a specific version
      version     = "0.24.4"
      namespace                 = var.namespace
      stage                     = var.stage
      name                      = var.name
      attributes                = var.attributes
      tags                      = var.tags
      subnet_ids                = module.subnets.public_subnet_ids
      instance_types            = var.instance_types
      desired_size              = var.desired_size
      min_size                  = var.min_size
      max_size                  = var.max_size
      cluster_name              = module.eks_cluster.eks_cluster_id
      kubernetes_version        = var.kubernetes_version
    }
```

Run `terraform init` and you'll see the versions are unhappy.

```
Error: Unresolvable module version constraint

There is no available version of module "cloudposse/security-group/aws"
(.terraform/modules/jhub.eks_node_group/security-group.tf:3) which matches the
given version constraint. The newest available version is 0.4.0.
```

You can also just go to the version lists on the terraform registry to see the discrepancy in versions:

If you look [here](https://registry.terraform.io/modules/cloudposse/eks-node-group/aws/0.24.4#module_security_group) you'll see that security_group version is `0.3.3`, but https://registry.terraform.io/modules/cloudposse/security-group/aws/latest doesn't list a version `0.3.3`, only `0.3.1`, `0.4.0`.

**Comment by mikedizon** [comment]
+1

**Comment by osterman** [comment]
This was resolved today. Sorry about that.
